/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini.project;

import hangman.Hangman;
import connectfour.Connect4;
import DotsAndBox.Dots;
import ludo.GameScreen;
import java.io.*;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class StartingInterface extends javax.swing.JFrame {

    /**
     * Creates new form StartingInterface
     */
    public static Player1 p1;
    public StartingInterface() {
        ImageIcon imgIcon = new ImageIcon ("D:\\Mini Project\\LogoSample_ByTailorBrands.jpg");
        JOptionPane.showMessageDialog(null, "Welcome to Game Hub", "Welcome", javax.swing.JOptionPane.INFORMATION_MESSAGE,imgIcon);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangmanB = new java.awt.Button();
        connectFourB = new java.awt.Button();
        connectTheDotsB = new java.awt.Button();
        ludoB = new java.awt.Button();
        gameHubLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Hub");

        hangmanB.setLabel("Hangman");
        hangmanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hangmanBActionPerformed(evt);
            }
        });

        connectFourB.setLabel("Connect Four");
        connectFourB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectFourBActionPerformed(evt);
            }
        });

        connectTheDotsB.setLabel("Connect The Dots");
        connectTheDotsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectTheDotsBActionPerformed(evt);
            }
        });

        ludoB.setLabel("Ludo");
        ludoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ludoBActionPerformed(evt);
            }
        });

        gameHubLabel.setLabelFor(this);

        jButton1.setText("LeaderBoard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LeaderBoard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("LeaderBoard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("LeaderBoard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Choose a Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangmanB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectFourB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectTheDotsB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ludoB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(gameHubLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hangmanB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectFourB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectTheDotsB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ludoB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(gameHubLabel)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Choose a Game");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hangmanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hangmanBActionPerformed
        // TODO add your handling code here:
        
         try{
            Player1 p1 = new Player1();
            p1.set_game("Hangman");
            p1.show();
        }
        catch (Exception E)
        {
            System.out.println ("Error" + E);
        }
    }//GEN-LAST:event_hangmanBActionPerformed

    private void connectFourBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectFourBActionPerformed
        // TODO add your handling code here:
        try{
            Player1 p1 = new Player1();
            p1.set_game("ConnectFour");
            p1.show();
        }
        catch (Exception E)
        {
            System.out.println ("Error" + E);
        }
        
    }//GEN-LAST:event_connectFourBActionPerformed

    private void connectTheDotsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectTheDotsBActionPerformed
        // TODO add your handling code here:
            Player1 p1 = new Player1();
            p1.set_game("ConnectTheDots");
            p1.show();
    }//GEN-LAST:event_connectTheDotsBActionPerformed

    private void ludoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ludoBActionPerformed
        // TODO add your handling code here:
        
        p1 = new Player1();
        p1.set_game("Ludo");
        p1.show();
    }//GEN-LAST:event_ludoBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/newdatabase","root2","password");  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from HangmanLeaderBoard order by wins desc"); 
            String s = "";
            int pos = 1;
             s = "Position\tName\tWins\tLost\n";
            while(rs.next())
            {
                s += pos +"\t"+rs.getString(1)+"\t"+rs.getInt(2)+"\t"+rs.getInt(3)+"\n";  
                pos++;
            }
            LeaderBoard l = new LeaderBoard();
            l.jTextArea1.setText(s);
            l.jTextArea1.setEditable(false);
            l.show();
            con.close();  
        }catch(Exception e){ System.out.println(e);} 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/newdatabase","root2","password");  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from ConnectFourLeaderBoard order by wins desc"); 
            String s = "";
            int pos = 1;
            s = "Position\tName\tWins\tLost\n";
            while(rs.next())
            {
                s += pos +"\t"+rs.getString(1)+"\t"+rs.getInt(2)+"\t"+rs.getInt(3)+"\n";  
                pos++;
            }
            LeaderBoard l = new LeaderBoard();
            l.jTextArea1.setText(s);
            l.jTextArea1.setEditable(false);
            l.show();
            con.close();  
        }catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/newdatabase","root2","password");  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from ConnectTheDotsLeaderBoard order by wins desc"); 
            String s = "";
            int pos = 1;
            s = "Position\tName\tWins\tLost\n";
            while(rs.next())
            {
                s += pos +"\t"+rs.getString(1)+"\t"+rs.getInt(2)+"\t"+rs.getInt(3)+"\n";  
                pos++;
            }
            LeaderBoard l = new LeaderBoard();
            l.jTextArea1.setText(s);
            l.jTextArea1.setEditable(false);
            l.show();
            con.close();  
        }catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/newdatabase","root2","password");  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from LudoLeaderBoard order by wins desc"); 
            
            int pos = 1;
            String s = "Position\tName\tWins\tLost\n";
            while(rs.next())
            {
                s += pos +"\t"+rs.getString(1)+"\t"+rs.getInt(2)+"\t"+rs.getInt(3)+"\n";  
                pos++;
            }
            LeaderBoard l = new LeaderBoard();
            l.show();
            l.jTextArea1.setEditable(false);
            l.jTextArea1.setText(s);
            con.close();  
        }catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button connectFourB;
    private java.awt.Button connectTheDotsB;
    private javax.swing.JLabel gameHubLabel;
    private java.awt.Button hangmanB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private java.awt.Button ludoB;
    // End of variables declaration//GEN-END:variables
}
